### ISSUE TITLE
CLI error: Error: spawn java ENOENT.

### ISSUE THREAD

**Issue by Head** [Samourai-Wallet/whirlpool-gui#4]
Downloaded the 0.7.0 .exe for Windows and got `CLI error: Error: spawn java ENOENT.`
```
[2019-07-02 14:22:00.402] [info] [CLI_LOCAL] => start: java -jar whirlpool-client-cli-0.7.0-run.jar --listen --debug --whirlpool-cli-gui (cwd=C:\Users\xxx\AppData\Roaming\whirlpool-gui)
[2019-07-02 14:22:00.429] [error] [CLI_LOCAL] =>  Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by zeroleak** [comment]
hello,
please make sure Java is installed and added to PATH and then try relaunching Whirlpool GUI. 
OpenJDK tends to work smoother than Oracle version of Java.
See #2

**Comment by Head** [comment]
That did the trick!
