### ISSUE TITLE
CLI error: Could not fetch CLI_API 0.9. in ubuntu 18.04 bionic.

### ISSUE THREAD

**Issue by cristianjs19** [Samourai-Wallet/whirlpool-gui#60]
I'm getting this issue after run the installation:
![Captura de pantalla de 2023-07-12 04-55-04](https://github.com/Samourai-Wallet/whirlpool-gui/assets/17844964/e10f1815-765b-42c7-a64f-20bf68901a48)
![Captura de pantalla de 2023-07-12 04-55-13](https://github.com/Samourai-Wallet/whirlpool-gui/assets/17844964/188c85e2-39bd-4d4f-bd57-84a3d01c953f)

[whirlpool-gui.log](https://github.com/Samourai-Wallet/whirlpool-gui/files/12025400/whirlpool-gui.log)

```
[2023-07-12 04:31:56.216] [info] CLI reloading...
[2023-07-12 04:31:56.712] [info] cliService is not configured.
[2023-07-12 04:31:56.717] [info] cliService.setCliLocal: true
[2023-07-12 04:31:56.723] [info] CLI reloading...
[2023-07-12 04:31:57.596] [info] using CLI_API 0.9 undefined
[2023-07-12 04:31:57.649] [error] Could not fetch CLI_API 0.9 TypeError: Cannot read property 'CLI_VERSION' of undefined
    at J.refreshState (/opt/whirlpool-gui/resources/app.asar/app/webpack:/app/mainProcess/cliLocal.js:179:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2023-07-12 04:31:57.846] [info] using CLI_API 0.9 undefined
[2023-07-12 04:31:57.847] [error] Could not fetch CLI_API 0.9 TypeError: Cannot read property 'CLI_VERSION' of undefined
    at J.refreshState (/opt/whirlpool-gui/resources/app.asar/app/webpack:/app/mainProcess/cliLocal.js:179:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2023-07-12 04:34:53.160] [info] whirlpool-gui is terminating.
```

OS info:
Kernel: 5.4.0-137-generic x86_64 bits: 64 compiler: gcc 
v: 7.5.0 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM 
Distro: Linux Mint 19.3 Tricia 
base: Ubuntu 18.04 bionic

**Comment by cristianjs19** [comment]
Solved in later releases, i'm clossing the issue.
